package com.oliinyk.yaroslav.easyreads.domain.util

object AppConstants {
    const val SECONDS_IN_ONE_HOUR = 3600
    const val SECONDS_IN_ONE_MINUTE = 60
    const val MINUTES_IN_ONE_HOUR = 60

    const val MILLISECONDS_IN_ONE_SECOND = 1000L
    const val MILLISECONDS_IN_ONE_MINUTE = 60000L

    val MINUTES_ALLOWED_RANGE = 0..59
    val SECONDS_ALLOWED_RANGE = 0..59

    const val READ_TIME_COUNTER_SERVICE_ID = 1
    const val FIREBASE_CLOUD_MESSAGING_SERVICE_ID = 2

    const val READ_TIME_COUNTER_NOTIFICATION_CHANNEL_ID = "READ_TIME_COUNTER_NOTIFICATION_CHANNEL"
    const val FIREBASE_CLOUD_MESSAGING_NOTIFICATION_CHANNEL_ID = "FIREBASE_CLOUD_MESSAGING_NOTIFICATION_CHANNEL_ID"

    const val BOOK_PAGE_AMOUNT_MAX_LENGTH = 4
    const val BOOK_ISBN_MAX_LENGTH = 13

    const val COPY_IMAGE_BUFFER_SIZE = 1024 * 8

    const val DATABASE_VERSION = 12
    const val MIME_TYPE_APPLICATION_ZIP = "application/zip"

    const val BACKUP_FILE_NAME = "backup-data.json"
}
